name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/my-app

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            set -e  # Exit on error
            cd /home/ubuntu/my-app

            # Install PM2 if missing
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Install dependencies and restart app
            npm install
            pm2 delete my-app || true
            pm2 start npm --name "my-app" -- run start
            pm2 save  # Save process list for restarts
          EOF
