name: Continuous integration

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Mocha tests
        run: |
          npm test

      - name: Audit Dependencies
        run: npm audit
        continue-on-error: true

      - name: Run ESLint
        run: npx eslint .
